# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2adc8190133c522ea0b5736b6306c856d3789ce902a6860cbe2ada820ce97435cce938463cce491fa1cbea03aaabaff4267ad4cccf87185553ad2c7df8e6f197

test:
  secret_key_base: 1c95c561678bc8f6d90391e96320c246969fa6a84927b20e82076219fe82fd1db73b6676aadb67d22707f629d8e11b4b9624f16e3be1e4eb4e3a22a634e43d7d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
